<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'name' => 'Chicken Burger',
                'slug' => Str::slug('Chicken Burger'),
                'thumb_image' => 'frontend/images/menu2_img_1.jpg',
                'category_id' => 4,
                'short_description' => "A juicy, breaded chicken patty served in a soft bun, often topped with fresh lettuce, creamy mayo, and crisp pickles.",
                'long_description' => "A chicken burger features a tender, seasoned chicken patty as its star. This can be grilled, fried, or breaded and crispy. It's nestled in a soft burger bun, often toasted for texture. Common toppings include fresh lettuce, ripe tomato, and creamy mayonnaise. Cheese, pickles, or bacon are popular additions, creating a satisfying and versatile handheld meal beloved for its juicy flavor and delightful combination of textures.",
                'price' => 100,
                'offer_price' => 80,
                'quantity' => 100,
                'sku' => 'BURGER-100',
                'seo_title' => '',
                'seo_description' => '',
                'show_at_home' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beef Burger',
                'slug' => Str::slug('Beef Burger'),
                'thumb_image' => 'frontend/images/menu2_img_1.jpg',
                'category_id' => 4,
                'short_description' => "A juicy grilled beef patty, nestled in a soft bun, topped with crisp lettuce, ripe tomato, and creamy sauces. A classic, satisfying meal.",
                'long_description' => "A beef burger is a classic sandwich featuring a grilled or fried ground beef patty, nestled within a soft bun. Typically topped with crisp lettuce, ripe tomato, and onion, it's often enhanced with cheese, pickles, and condiments like ketchup or mustard. This hearty, hand-held meal is a global icon of casual dining, celebrated for its satisfying, savory flavors and customizable nature.",
                'price' => 90,
                'offer_price' => 70,
                'quantity' => 100,
                'sku' => 'BURGER-110',
                'seo_title' => '',
                'seo_description' => '',
                'show_at_home' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chicken Fried Rice',
                'slug' => Str::slug('Chicken Fried Rice'),
                'thumb_image' => 'frontend/images/menu2_img_2.jpg',
                'category_id' => 3,
                'short_description' => "A quick wok-tossed dish of rice, chicken, vegetables, and egg, seasoned with soy sauce for a savory, satisfying meal.",
                'long_description' => "Chicken fried rice is a beloved stir-fried dish featuring tender pieces of chicken, fluffy rice, and a colorful mix of vegetables like peas and carrots. It's quickly cooked in a hot wok with soy sauce, garlic, and often a touch of egg. This savory, satisfying meal is a staple of Asian cuisine, prized for its simple ingredients and incredible flavor, making it a perfect quick and complete dinner.",
                'price' => 70,
                'offer_price' => 50,
                'quantity' => 100,
                'sku' => 'CHICKEN-100',
                'seo_title' => '',
                'seo_description' => '',
                'show_at_home' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chicken Fried',
                'slug' => Str::slug('Chicken Fried'),
                'thumb_image' => 'frontend/images/menu2_img_7.jpg',
                'category_id' => 3,
                'short_description' => "A country anthem celebrating simple joys: cold beer, a comforting meal, and American pride.",
                'long_description' => "Chicken Fried is a celebratory country anthem by the Zac Brown Band. The song uses the simple comfort of crispy, golden chicken fried steak as a powerful metaphor for appreciating life's fundamental joys. Its lyrics express deep gratitude for cherished small-town values, everyday pleasures, and beloved family, reminding listeners to savor these simple blessings as the true ingredients of a rich and fulfilling life.",
                'price' => 60,
                'offer_price' => 50,
                'quantity' => 100,
                'sku' => 'CHICKEN-110',
                'seo_title' => '',
                'seo_description' => '',
                'show_at_home' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Greek Pizza',
                'slug' => Str::slug('Greek Pizza'),
                'thumb_image' => 'frontend/images/menu2_img_4.jpg',
                'category_id' => 2,
                'short_description' => "Greek pizza features a thick, chewy crust, topped with olive oil, oregano, and simple ingredients like feta cheese and olives.",
                'long_description' => "Greek pizza is a distinct style popular in New England. It is characterized by a thick, chewy, and airy crust cooked in a shallow, heavily oiled pan, giving the bottom a fried, almost focaccia-like texture. Toppings are typically generous, featuring a rich, tangy tomato sauce and a blend of oregano and grated cheeses like a kasseri-romano mix, rather than standard mozzarella.",
                'price' => 70,
                'offer_price' => 50,
                'quantity' => 100,
                'sku' => 'PIZZA-100',
                'seo_title' => '',
                'seo_description' => '',
                'show_at_home' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chicago Pizza',
                'slug' => Str::slug('Chicago Pizza'),
                'thumb_image' => 'frontend/images/menu2_img_8.jpg',
                'category_id' => 2,
                'short_description' => "Chicago pizza features a deep, buttery crust, thick layers of cheese, and chunky tomato sauce, often baked in a tall, round pan.",
                'long_description' => "Chicago pizza is a deep-dish style originating in the 1940s. Characterized by its tall, buttery crust, it is built like a pie with layers of cheese, fillings like sausage, and a chunky tomato sauce on top. Baked in a deep pan, it results in a hearty, fork-and-knife meal, setting it apart from its thin-crust counterparts. It is a defining icon of the city's culinary scene.",
                'price' => 50,
                'offer_price' => 40,
                'quantity' => 100,
                'sku' => 'PIZZA-110',
                'seo_title' => '',
                'seo_description' => '',
                'show_at_home' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cakes',
                'slug' => Str::slug('Cakes'),
                'thumb_image' => 'frontend/images/menu2_img_8.jpg',
                'category_id' => 1,
                'short_description' => "Sweet, baked desserts, often layered and frosted. Celebrated for birthdays, weddings, and as a delightful indulgence for any special occasion.",
                'long_description' => "Cakes are celebratory baked delights, often layered or single-tiered. Their tender crumb comes from creaming butter and sugar, then adding eggs and flour. While vanilla and chocolate are classics, countless flavors exist. Frostings like buttercream or ganache add richness and decoration. From simple birthday cakes to elaborate wedding creations, they are synonymous with joy and marking life’s sweetest moments.",
                'price' => 30,
                'offer_price' => 20,
                'quantity' => 100,
                'sku' => 'CAKES-100',
                'seo_title' => '',
                'seo_description' => '',
                'show_at_home' => 1,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
